name: CI

on:
  workflow_dispatch:

jobs:
  skip-if-fork:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run your steps
        run: echo "This PR is from the same repo, running workflow..."
