name: test

on:
  pull_request_target:

jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
    - name: Get repository name
      id: check
      run: |
        REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d "/" -f 2)
        echo "repo=$REPO_NAME" >> $GITHUB_OUTPUT
  
  build:
    runs-on: ubuntu-latest
    outputs:
      build_result: ${{ steps.check_build.outputs.build_result }}
    steps:
    - name: Get repository name
      id: check_build
      run: |
        echo "build_result=success" >> $GITHUB_OUTPUT
        exit 1
        
        sleep 50
  
  sonar:
    runs-on: ubuntu-latest
    outputs:
      sonar_result: ${{ github.check_sonar.outputs.sonar_result }}
    steps:
    - name: Get repository name
      id: check_sonar
      run: |
        sleep 20
        echo "sonar_result=success" >> $GITHUB_OUTPUT

  approve:
    needs: [readme, build, sonar]
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: Get repository name
      run: |
        echo build:${{ needs.build.outputs.build_result }} 
        echo sonar:${{ needs.sonar.outputs.sonar_result }}
